---
- name: set fact for later use
  hosts: frontend[0]
  sudo: yes
  tasks:
     # you can't use delegate_to and register at simultaneously
     # delegate_to is used for simple "fire and forget" command.
    - name: determine tenant id of "service"
      shell: >
        /usr/bin/keystone 
        --os-endpoint "{{ keystone_admin_url }}" 
        --os-token "{{ admin_token }}"
        tenant-get {{service_tenant}}  | grep "id " | awk {'print $4'}      
      register: nova_admin_tenant_id
    
    - name: set_fact nova_admin_tenant_id for later use
      action: set_fact
      args: 
        admin_tenantID: "{{ nova_admin_tenant_id.stdout }}"

- name: OpenStack Networking (Network Gateway)
  hosts: network_gateway
  sudo: yes
  tasks:
    - name: ensure neutron packages are installed
      yum: name={{ item }} state=latest
      with_items:
        - MySQL-python
        - openstack-neutron
        - openstack-neutron-ml2
        - openstack-neutron-openvswitch
        - openstack-neutron-linuxbridge
        - openstack-utils
        - openstack-selinux
        - python-neutron
        - python-neutronclient
        - haproxy
      notify:
        - restart neutron-agents(gateway)

      
    - name: ensure neutron configuration files are copied
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: neutron
        mode: 0640
      with_items: 
        - { src: templates/etc/neutron/neutron.conf, dest: /etc/neutron/neutron.conf}
        - { src: templates/etc/neutron/plugins/ml2/ml2_conf_linuxbridge_VLAN.ini, dest: /etc/neutron/plugins/ml2/ml2_conf.ini}
        - { src: templates/etc/neutron/dhcp_agent.ini, dest: /etc/neutron/dhcp_agent.ini}
        - { src: templates/etc/neutron/l3_agent.ini, dest: /etc/neutron/l3_agent.ini}
        - { src: templates/etc/neutron/lbaas_agent.ini, dest: /etc/neutron/lbaas_agent.ini}
        - { src: templates/etc/neutron/metadata_agent.ini, dest: /etc/neutron/metadata_agent.ini }
      notify:
        - restart neutron-agents(gateway)
          
    - name: ensure symlink to ml2 plugin is created.
      file: src=/etc/neutron/plugins/ml2/ml2_conf.ini
            path=/etc/neutron/plugin.ini
            state=link
      notify:
        - restart neutron-agents(gateway)

      
    - name: ensure neutron-linuxbridge-agent reads symlink
      copy:
        src: templates/etc/init.d/neutron-linuxbridge-agent
        dest: /etc/init.d/neutron-linuxbridge-agent
        owner: root
        group: root
        mode: 0755
      notify:
        - restart neutron-agents(gateway)
        
        
    - name: ensure neutron-linuxbridge-agent automatically boots after reboot
      service: name=neutron-linuxbridge-agent state=started enabled=yes 
        
    - name: ensure neutron-dhcp-agent automatically boots after reboot
      service: name=neutron-dhcp-agent state=started enabled=yes
               
    - name: ensure L3-agent automatically boots after reboot
      service: name=neutron-l3-agent state=started enabled=yes

    - name: ensure neutron-metadata-agent automatically boots after reboot
      service: name=neutron-metadata-agent state=started enabled=yes

    - name: ensure neutron-lbaas-agent automatically boots after reboot
      service: name=neutron-lbaas-agent state=started enabled=yes 

      
    - name: (WORKAROUND) comment out FORWARD REJECT rule from iptables to enable instace DHCP
      include: ../reusables/delete_firewall_rule.yml delete_line='-A FORWARD -j REJECT --reject-with icmp-host-prohibited'
      
      
      
      
     
      
  handlers:
    - name: restart neutron-agents(gateway)
      service: name={{ item }} state=restarted
      with_items:
       - neutron-dhcp-agent
       - neutron-l3-agent
       - neutron-lbaas-agent
       - neutron-linuxbridge-agent
       - neutron-metadata-agent

    - include: ../reusables/handlers.yml
       
