---
- name: MySQL Server
  hosts: sql_backend
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure mysql and mysql python client installed
      yum: name={{ item }} state=latest
      with_items:
        - mysql-server
        - MySQL-python
#      notify:
#        - stop mysql
  
    - name: ensure mysql port is opened.
      include: ../reusables/open_firewall_port.yml protocol=tcp port=3306

 
    - name: ensure my.cnf file is configured
      copy: >
            src=templates/etc/my.cnf
            dest=/etc/my.cnf
            owner=root
            group=root
            mode=0664
      notify:
        - restart mysql

    - name: ensure mysql runs automatically after boot.
      service: name=mysqld state=restarted enabled=yes

    - name: ensure mysql root password for all root accounts are changed (1 of 2)
      mysql_user: >
            name=root
            host={{ item }}
            password={{ root_db_password }}
      with_items: 
        - "{{ my_int_ip }}"
        - 127.0.0.1
        - "{{ ansible_fqdn }}"
        - localhost

    
        
        
    - name: ensure .my.cnf file is configured
      template: >
            src=templates/root/.my.cnf
            dest=/root/.my.cnf
            owner=root
            mode=0600
      
            
    - name: reboot mysqld and refresh configuration
      service: name=mysqld state=restarted enabled=yes
  

    - name: ensure anonymous users are not in the database
      mysql_user: >
            name=''
            host={{ item }}
            state=absent
      with_items: 
            - localhost
            - "{{ ansible_fqdn }}"

    - name: ensure TEST database is removed
      mysql_db: >
            name="test"
            state=absent

  handlers:
    - include: ../reusables/handlers.yml

    - name: stop mysql
      service: name=mysqld state=restarted
      when: "ansible_hostname != primary_controller_host"

    - name: restart mysql
      service: name=mysqld state=restarted
#      when: "ansible_hostname == primary_controller_host"

